CREATE TABLE "public"."order_payments" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "order_id" UUID NOT NULL REFERENCES "public"."orders" ("id"),
  "amount" NUMERIC(10, 2) NOT NULL, -- Valor em R$
  "due_date" DATE,
  "status" "public"."payment_status" DEFAULT 'Pending'
);

CREATE TABLE "public"."purchase_orders" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "supplier_name" TEXT,
  "nf_attachment_url" TEXT, -- Link para o Supabase Storage (Anexo NF)
  "received_at" TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE "public"."purchase_order_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "purchase_order_id" UUID NOT NULL REFERENCES "public"."purchase_orders" ("id") ON DELETE CASCADE,
  "product_id" UUID NOT NULL REFERENCES "public"."products" ("id"),
  "quantity_received" INT NOT NULL
);